# Generated by Django 5.2.7 on 2026-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
    ]
