# Generated by Django 5.2.7 on 2026-01-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='logo_url',
            new_name='image',
        ),
    ]
